In [12]:
from ipywidgets import *
from traitlets import dlink
def f(x):
    if x == 1 or x==0:
        return x
    else:
        return x+f(x-1)
interact(f,x=(0,100));


interactive(children=(IntSlider(value=50, description='x'), Output()), _dom_classes=('widget-interact',))

In [13]:
from ipyleaflet import Map

Map(center=[34.6252978589571, -77.34580993652344], zoom=10)

ModuleNotFoundError: No module named 'ipyleaflet'

In [14]:
import IPython.display as disp


In [15]:
%matplotlib inline
# import ipympl
import matplotlib.pyplot as plt
# from bqplot import pyplot as plt
import numpy as np
def f(m,b):
    plt.figure()
    x = np.linspace(-10,10,1000)
    y = m*x +b
    plt.plot(x,y)
    plt.ylim(-5,5)
    plt.show()
interactive_plot = interactive(f,m=(-2.0,2.0),b=(-3,3,0.5))
# output = interactive_plot.children(-1)
# output.layout.height = '300px'
interactive_plot
    

interactive(children=(FloatSlider(value=0.0, description='m', max=2.0, min=-2.0), FloatSlider(value=0.0, descr…

In [16]:

from bqplot import pyplot as plt
import numpy as np

plt.figure()
n = 200
x = np.linspace(0,100,n)

y = np.cumsum(np.random.random(n)-0.5)

plt.plot(x,y)
plt.show()

In [17]:
plt.figure()
plt.plot(np.random.randn(200))
plt.show()

In [18]:
from bqplot import *
from IPython.display import display

x_data = range(10)
y_data = [i ** 2 for i in x_data]

x_sc = LinearScale()
y_sc = LinearScale()

ax_x = Axis(label='Test X', scale=x_sc, tick_format='0.0f')
ax_y = Axis(label='Test Y', scale=y_sc,
            orientation='vertical', tick_format='0.2f')

line = Lines(x=x_data,
             y=y_data,
             scales={'x': x_sc, 'y': y_sc},
             colors=['red', 'yellow'])

fig = Figure(axes=[ax_x, ax_y], marks=[line])

display(fig)

Figure(axes=[Axis(label='Test X', scale=LinearScale(), tick_format='0.0f'), Axis(label='Test Y', orientation='…

In [19]:
import numpy as np

from bqplot import pyplot as plt
size = 100
# np.random.seed(0)
x_data = np.arange(size)
y_data = np.cumsum(np.random.randn(size)  * 100.0)

plt.figure(title='My First Plot')
plt.plot(x_data, y_data)
plt.show()


In [20]:
plt.figure(title='My Second Chart')
scatter_plot = plt.scatter(x_data, y_data)
plt.show()

In [21]:
scatter_plot.y = np.cumsum(np.random.randn(size)  * 100.0)
scatter_plot.colors = ['Red']
# scatter_plot.marker = 'diamond'

In [22]:
def foo(change):
    print('This is a trait change. Foo was called by the fact that we moved the Scatter')
    print('In fact, the Scatter plot sent us all the new data: ')
    print('To access the data, try modifying the function and printing the data variable')

In [23]:
scatter_plot.observe(foo, 'y')
scatter_plot.enable_move = True

In [24]:
import numpy as np
import bqplot.pyplot as plt
from bqplot import *

# ======================= Line Animations ===============================
axes_options = {'x': {'label': 'x'}, 'y': {'label': 'y'}}

x = np.arange(100)
z = np.random.randn(2, 100)
y = np.cumsum(z, axis=1) #two random walks

fig = plt.figure(animation_duration=1500)
lines = plt.plot(x=x,y=y, colors=['red', 'green'], axes_options=axes_options)

fig


Figure(animation_duration=1500, axes=[Axis(label='x', scale=LinearScale()), Axis(label='y', orientation='verti…

In [25]:
# 以下代码每次运行均会更新线条
# update data of the line mark
import time
for _ in range(10):
    lines.y = np.cumsum(np.random.randn(2, 100), axis=1)
    time.sleep(1.5)


In [26]:
arr = np.arange(9).reshape((3, 3))
print(arr)
np.random.shuffle(arr)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [0 1 2]
 [3 4 5]]
