https://ipython.readthedocs.io/en/stable/interactive/magics.html

In [108]:
%automagic # % prefix IS NOT needed for line magics.它具有最低优先级
# 试着两次运行它


Automagic is ON, % prefix IS NOT needed for line magics.


In [114]:
time

Wall time: 0 ns


### ? and ??
? 访问帮助文档  
?? 访问源码

In [118]:
import numpy as np
np.argwhere?

Signature: np.argwhere(a)
Docstring:
Find the indices of array elements that are non-zero, grouped by element.

Parameters
----------
a : array_like
    Input data.

Returns
-------
index_array : ndarray
    Indices of elements that are non-zero. Indices are grouped by element.

See Also
--------
where, nonzero

Notes
-----
``np.argwhere(a)`` is the same as ``np.transpose(np.nonzero(a))``.

The output of ``argwhere`` is not suitable for indexing arrays.
For this purpose use ``nonzero(a)`` instead.

Examples
--------
>>> x = np.arange(6).reshape(2,3)
>>> x
array([[0, 1, 2],
       [3, 4, 5]])
>>> np.argwhere(x>1)
array([[0, 2],
       [1, 0],
       [1, 1],
       [1, 2]])
File:      c:\miniconda\envs\tf2\lib\site-packages\numpy\core\numeric.py
Type:      function


In [144]:
a = np.arange(10).reshape(2,-1)
print(a)
np.argwhere(a>2)
# np.transpose(np.nonzero(a>2))

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[0, 3],
       [0, 4],
       [1, 0],
       [1, 1],
       [1, 2],
       [1, 3],
       [1, 4]], dtype=int64)

### line magic
在IPython中，指令分为两种，以%开头的叫做line magic，这种类型的指令只能作用与一行代码，如

In [13]:
# %time 执行一次的时间， %timeit 执行多次的平均时间
%timeit a = 1

12.6 ns ± 2.64 ns per loop (mean ± std. dev. of 7 runs, 100000000 loops each)


### cell magic
以%%开头的叫做cell magic，这种类型的指令可以作用于一个代码块，比如：

In [14]:
%%timeit
def f(n):
    if n == 0 or n == 1:
        return n
    return f(n-1) + f(n-2)
    
f(20)

3.41 ms ± 821 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


### `%run xxx.py` 
可以运行一个外部的python script，并把运行结果导入到当前的IPython上下文环境，好比说外部脚本定义了一个变量a，那么通过`%run`运行这个脚本之后就可以在IPython中继续使用这个变量。  


### ！
在IPython中可以很方便的使用Linux命令，只需要一个!就可以，比如:

In [9]:
name = !echo hello

In [10]:
name

['hello']

###  $
把Python的变量结合到Linux命令中，比如:

In [11]:
name = "My name is Sam"

In [12]:
!echo $name

My name is Sam


### %cd directory 
将系统工作目录更改为directory

### %reset
删除interactive命名空间中全部的变量名，有时可能要加上-f

### %magic 
查看魔术命令

%alias alias_name cmd 为系统shell命令定义别名
%alias ll ls -l 将ll作为ls -l的别名暂时保存
%who、%who_ls、%whos 显示interactive命名空间中定义的变量，信息级别/冗余度可变
%hist 历史命令  
%pwd 返回系统的当前工作目录
%dirs 返回一个含有当前目录栈的列表
%env 以dict形式返回系统环境变量

In [130]:
who_ls

['a', 'f', 'i', 'name', 'os']