# 使用dill库可方便存储和恢复会话中所有变量

In [3]:
import dill

In [13]:
import numpy as np
import librosa
import librosa.display
import IPython.display as ipd
import matplotlib.pyplot as plt

In [18]:
a = np.linspace(0, 200*pi, 10000)
x = 10 * np.cos(a)
y = 10 * np.sin(a)
res = ipd.Audio(y,rate=10000)
res

In [19]:
dill.dump_session('lalala.pkl')

In [20]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])?  y


In [21]:
res

NameError: name 'res' is not defined

In [22]:
import dill
dill.load_session('lalala.pkl')

In [23]:
res

# 对于numpy中的npy 和 npz文件的存储与恢复

In [2]:
# 对于单个数组的存储可以直接用np.save, 以.npy文件存储
a = np.arange(10)
np.save('a.npy', a)

# 恢复
a = np.load('a.npy')
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# 对于多个数组存放到一个文件中,使用np.savez(), 以.npz文件存储
b = np.arange(15)
np.savez('ab.npz', a=a, b=b) # 给变量命名为a, b 方便字典提取

# 恢复
AB = np.load('ab.npz')
a = AB['a']
b = AB['b']
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
